name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/${{ github.repository_owner }}/hello-world:latest
        docker run ghcr.io/${{ github.repository_owner }}/hello-world:latest
        docker push ghcr.io/${{ github.repository_owner }}/hello-world:latest

